### ISSUE TITLE
smex failed when using ivy mode

### ISSUE THREAD

**Issue by johncming** [rakanalh/emacs-bootstrap#23]
Hi, when I use ivy mode and I find that below.

![qq20161221-0](https://cloud.githubusercontent.com/assets/11719334/21374281/976611cc-c760-11e6-8a87-1af042501102.png)

Working properly after I press M-x

![qq20161221-1](https://cloud.githubusercontent.com/assets/11719334/21374299/b83ad8f6-c760-11e6-8f38-651dfc0ed4bc.png)

How should I to modify the configration.

Thanks.

**Comment by rakanalh** [comment]
Hi... sorry but i don't seem to follow. Care to elaborate more on this issue? whats the smex failure you're referring to?

**Comment by johncming** [comment]
After emacs initialized, the autocomplete function work incorrect that have no hints of items like directories or files.

If I press M-x or C-x C-m, then the autocomplete function  work fine. I don't know how to do modify it. I havd try it below:

(smex-initialize)

but, it doesn't work.

**Comment by rakanalh** [comment]
Ah i see. This actually happens with me when i start Emacs... to be honest i haven't got to fixing this in my own configuration and i think this is an Ivy / counsel issue rather than a bootstrap issue.  Maybe you can file a ticket on Ivy's repo?
