### ISSUE TITLE
custom-file is set but never read

### ISSUE THREAD

**Issue by benlinkels** [rakanalh/emacs-bootstrap#27]
The location of the custom.el file can be altered in the base.el, but the value is never read back.

If the variable is altered from the default value, it will not be loaded after a restart of emacs. Just add this after the Emacs customization block:
`(load custom-file)

(add-hook 'kill-emacs-query-functions
    'custom-prompt-customize-unsaved-options)`

[saving customizations - emacs manual](https://www.gnu.org/software/emacs/manual/html_node/emacs/Saving-Customizations.html)

**Comment by Hettomei** [comment]
Hi,

Same here.

Just adding  inside base.el
```
(load custom-file)
```

Fix this bug that .customize.el is overwritten.
