### ISSUE TITLE
Error on org-projectile/:config

### ISSUE THREAD

**Issue by robsonpeixoto** [rakanalh/emacs-bootstrap#32]
Error (use-package): org-projectile/:config: Symbol’s function definition is void: org-projectile:per-repo.

https://github.com/rakanalh/emacs-bootstrap/blob/master/emacs_templates/emacs/elisp/base-extensions.el#L144-L148

**Comment by W73** [comment]
org-projectile owner did some changes

It is his pull request to spacemacs. 

https://github.com/syl20bnr/spacemacs/pull/9312/commits/74d699445830faa8f8f476780c6dd954e4433148

**Comment by robsonpeixoto** [comment]
Thanks @W73
