### ISSUE TITLE
Site is unreachable

### ISSUE THREAD

**Issue by PieterPaulussen** [rakanalh/emacs-bootstrap#36]
www.emacs-bootstrap.com is unreachable.

**Comment by Ambrevar** [comment]
No news?

**Comment by rakanalh** [comment]
Hi @PieterPaulussen and @Ambrevar 

Sorry for the late reply... i couldn't find the time to deploy it to a new server. But now it should be up and running. 

Out of curiosity, how is emacs-bootstrap useful to you?

Thanks for the report.

**Comment by Ambrevar** [comment]
It's working, thanks!

To satisfy your curiosity, I don't use emacs-bootstrap directly (my configuration is way to fine-tuned for that) but I think it's great as a starting point suggestion for newcomers.
I see emacs-bootstrap as a big selling point :)

**Comment by rakanalh** [comment]
Thanks @Ambrevar, that's the answer i wanted to hear. Am glad you're finding it useful to onboard other people to Emacs.

**Comment by PieterPaulussen** [comment]
@rakanalh Thanks for getting the website back up. I was actually just experimenting with your config generator.
Can I make 1 suggestion though? Could you add an option to not specify a default theme, I think both currently available themes are hideous. ;-)
