### ISSUE TITLE
http://emacs-bootstrap.com not available

### ISSUE THREAD

**Issue by mikeb-emacs** [rakanalh/emacs-bootstrap#53]
The Website doesn't seem to work at the moment.

**Comment by nickfun** [comment]
I'm getting back into emacs and remembered this site, but it also does not load for me. To be specific, the domain http://emacs-bootstrap.com loads up a site that looks like blog spam (rindent.com). 

The WHOIS shows:

```   
   Updated Date: 2019-11-06T11:08:53Z
   Creation Date: 2016-11-05T18:51:04Z
   Registry Expiry Date: 2020-11-05T18:51:04Z
```
@avelino are you the current maintainer? Did the domain expire and get grabbed by a squatter? It lists as expiring in a few months, maybe it can be recovered then?

**Comment by avelino** [comment]
@rakanalh help pls

**Comment by rakanalh** [comment]
I have shut down the server on linode and have no plans to restore it. I am happy to transfer ownership of the domain to whoever wants to host the app.

**Comment by avelino** [comment]
> I have shut down the server on linode and have no plans to restore it. I am happy to transfer ownership of the domain to whoever wants to host the app.

@rakanalh set this DNS on domain
- ivan.ns.cloudflare.com
- sara.ns.cloudflare.com

I configure the environment in vim-bootstrap hosting

**Comment by rakanalh** [comment]
Done

**Comment by avelino** [comment]
@rakanalh upgrade dns to:

- greg.ns.cloudflare.com
- selah.ns.cloudflare.com

site on here: https://emacs-bootstrap.herokuapp.com/

**Comment by rakanalh** [comment]
Updated the DNS records.

**Comment by nickfun** [comment]
Thanks y'all for getting it back online. It works fine for me now at https://emacs-bootstrap.com/. 🙇‍♂️
